### ISSUE TITLE
Make the lachesis-rs crate pure and architecture agnostic

### ISSUE THREAD

**Issue by rishflab** [Fantom-foundation/lachesis-rs#12]
IMO we should make the lachesis-rs crate (and another other consensus crates) pure and architecture agnostic. We shouldnt have any threads, mutexes etc. It should just be data structures and the algorithms that operate on those data structures. We should be able to use the consensus crate with any thread/networking architecture.

**Comment by AgustinCB** [comment]
I don't agree with this.

First, because I'd argue that thread safety it's not an architecture decision, it's a feature of a data structure.

And second, because moving thread safety up the abstraction tree (a consequence of this issue) means an important lose on performance. By having the mutexes in the node, we are able to specify _exactly_ which parts needs to be locked. If we put the mutex on `Node` as a whole, we are locking every operation made on that data structure and losing a lot of parallelism.

**Comment by rishflab** [comment]
I was hoping we could create/use lock free data structures.
https://github.com/crossbeam-rs/crossbeam
https://www.cs.cmu.edu/~410-s05/lectures/L31_LockFree.pdf
I am still looking into it, the primary issue I am seeing is that lock free data structures are hard to implement.

**Comment by AgustinCB** [comment]
Uhm, that's a different topic and I agree that it'd be nice.

But we would need lock free sets and hash maps and that's a _really_ complicated topic that I'm not sure it's worth exploring at this point.

If we find a library already implementing it, I'm totally onboard. It'd make everything easier and prettier. If we don't, I feel very hesitant to implement ourselves.

**Comment by rishflab** [comment]
I was looking at these libraries:

https://github.com/slide-rs/shred
https://github.com/slide-rs/specs

Specs has hashmap, vector, btree storages. Afaik they lock-free.

Additionally the programming model is really simple to understand.

1. Data is kept in storages. 
2. Systems can access the the data with read/write privledges
3. You can specify the system execution order dependencies
4. Sytems automatically run in parrallel on a thread pool
5. Storages can be iterated over using parrellel iterators.

I am keen to give specs a shot. Should be fairly straightforward to store the DAG in there and perform
consensus operations in systems. I think it should make the codebase easier to understand.

If we do this the data structures we use will be tied to these libraries so I guess you are right about threading and data structures being strongly linked.

**Comment by AgustinCB** [comment]
Uhm, interesting. Specs it's cool, although I never head of ECS being used efficiently outside gamedev or physics simulations. I'd not say that's easier to understand, I found that most programmer are familiar with oop or fp but when it comes to ecs it's a fairly alien subject and difficult to grasp. But if it works better in this case, sounds good to me! It's nothing we can't teach new devs.

I'd wait till I finish the testnet, though, to make sure we have a reliable way to compare implementations. Once we have that, feel free to refactor with your idea and compare how it works. I hope it works well, always wanted to try ECS outside games.

**Comment by SamuelMarks** [comment]
🤔, can we hide the mutexes behind macros, such that if we switch to a data-structure which doesn't need them, we can just turn off the flag with Cargo?

That way, down the track, we can do _actually_ correct benchmarks without code duplication.

**Comment by AgustinCB** [comment]
Fair idea.

We're already using a macro to abstract some of the logic behind mutexes: https://github.com/Fantom-foundation/lachesis-rs/blob/master/lachesis-rs/src/node.rs#L17. Right now, the overhead because of their presence it's as low as it gets in Rust.

We could go the extra mile and add more macros to make the use of mutexes a switch at compile time. It should be a pretty straight forward change.
